resources:
- kind: Desktop
  cpus:
  - model: Intel(R) Core(TM) i5-9500
    cores: 6
    threads: 6
  ram:
    size: 16
    mts: 2666
  drives:
  - type: ssd
    size: 512
  nics:
  - type: rj45
    speed: 1
    ports: 1
  gpus:
  - model: RTX 3080
    vram: 12
  model: 
  name: dell-optiplex
  tags: 
