resources:
  - kind: Laptop
    cpus:
      - model: Intel(R) Core(TM) i7-10510U
        cores: 4
        threads: 8
    ram:
      size: 16
      mts: 2666
    drives:
      - type: ssd
        size: 1024
    gpus:
      - model: RTX 3080
        vram: 12
    name: thinkpad-x1
    tags: 
