resources:
  - kind: Router
    model: ER-4
    managed: true
    poe: true
    ports:
      - type: rj45
        speed: 1
        count: 8
      - type: sfp
        speed: 10
        count: 2
    name: ubiquiti-edge-router
    tags: 
