resources:
  # --------------------------------------------------
  # Hypervisors (Bare Metal)
  # --------------------------------------------------
  - kind: System
    type: Hypervisor
    name: proxmox-cluster-node01
    os: proxmox
    cores: 16
    ram: 128gb
    drives:
      - size: 1tb
      - size: 1tb
    runsOn: proxmox-node01

  - kind: System
    type: Hypervisor
    name: proxmox-cluster-node02
    os: proxmox
    cores: 10
    ram: 96gb
    drives:
      - size: 1tb
      - size: 4tb
    runsOn: proxmox-node02

  # --------------------------------------------------
  # Storage OS (Bare Metal)
  # --------------------------------------------------
  - kind: System
    type: Baremetal
    name: truenas-core-os
    os: truenas
    cores: 6
    ram: 64gb
    drives:
      - size: 8tb
      - size: 8tb
      - size: 8tb
      - size: 8tb
    runsOn: truenas-storage

  # --------------------------------------------------
  # IPMI / BMC Management
  # --------------------------------------------------
  - kind: System
    type: Baremetal
    name: ipmi-proxmox-node01
    os: idrac
    cores: 1
    ram: 1gb
    runsOn: proxmox-node01

  - kind: System
    type: Baremetal
    name: ipmi-proxmox-node02
    os: ipmi
    cores: 1
    ram: 1gb
    runsOn: proxmox-node02

  - kind: System
    type: Baremetal
    name: ipmi-truenas-storage
    os: ipmi
    cores: 1
    ram: 1gb
    runsOn: truenas-storage

  # --------------------------------------------------
  # Core Network Systems
  # --------------------------------------------------
  - kind: System
    type: Baremetal
    name: firewall-os
    os: pfsense
    cores: 4
    ram: 8gb
    drives:
      - size: 32gb
    runsOn: pfsense-fw

  - kind: System
    type: Baremetal
    name: router-os
    os: edgeos
    cores: 4
    ram: 4gb
    drives:
      - size: 4gb
    runsOn: core-router

  - kind: System
    type: Baremetal
    name: unifi-core-switch-os
    os: unifi-os
    cores: 2
    ram: 2gb
    drives:
      - size: 8gb
    runsOn: core-switch

  - kind: System
    type: Baremetal
    name: unifi-access-switch-os
    os: unifi-os
    cores: 2
    ram: 2gb
    drives:
      - size: 8gb
    runsOn: access-switch

  - kind: System
    type: Baremetal
    name: unifi-lounge-ap-os
    os: unifi-firmware
    cores: 2
    ram: 1gb
    drives:
      - size: 4gb
    runsOn: lounge-ap

  # --------------------------------------------------
  # Virtual Machines
  # --------------------------------------------------
  - kind: System
    type: VM
    name: vm-home-assistant
    os: hassos
    cores: 2
    ram: 4gb
    drives:
      - size: 64gb
    runsOn: proxmox-node01

  - kind: System
    type: VM
    name: vm-media-server
    os: ubuntu-22.04
    cores: 4
    ram: 8gb
    drives:
      - size: 500gb
    runsOn: proxmox-node02

  - kind: System
    type: VM
    name: vm-monitoring
    os: debian-12
    cores: 2
    ram: 4gb
    drives:
      - size: 64gb
    runsOn: proxmox-node01